/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.62
 * Generated at: 2015-06-16 04:38:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.body;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css\">\r\n");
      out.write("<script src=\"//code.jquery.com/ui/1.11.4/jquery-ui.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"//apis.daum.net/maps/maps3.js?apikey=8090c845eb21bcc92becc6f8f3bf61fa&libraries=services\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/wheremasil/script/map_view.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("   ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("   ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("   $(function() {\r\n");
      out.write("      $(\"header\").css(\"background-color\", \"none\");\r\n");
      out.write("      $(\"section\").css(\"width\",\"1880px\");\r\n");
      out.write("      $(\"section\").css(\"height\",\"1300px\");\r\n");
      out.write("      $(\".left_nav\").css(\"width\", \"0px\");\r\n");
      out.write("      $(\".right_nav\").css(\"width\", \"0px\");\r\n");
      out.write("      $(\"#bs-example-navbar-collapse-1\").css(\"width\", \"1880px\");\r\n");
      out.write("\r\n");
      out.write("      $(\"#popup_cancel\").on(\"click\", function() {\r\n");
      out.write("         $(\"#popup_layer\").css(\"visibility\", \"hidden\");\r\n");
      out.write("      });\r\n");
      out.write("\r\n");
      out.write("      $(\"#stDate\").datepicker({\r\n");
      out.write("         dateFormat : 'yymmdd',\r\n");
      out.write("         minDate:0,\r\n");
      out.write("          onClose: function( selectedDate ) {\r\n");
      out.write("           $(\"#edDate\").datepicker( \"option\", \"minDate\", selectedDate );\r\n");
      out.write("          }\r\n");
      out.write("      });\r\n");
      out.write("      $(\"#edDate\").datepicker({\r\n");
      out.write("         dateFormat : 'yymmdd',\r\n");
      out.write("         minDate:0,\r\n");
      out.write("         onClose: function( selectedDate ) {\r\n");
      out.write("           $(\"#stDate\").datepicker( \"option\", \"maxDate\", selectedDate );\r\n");
      out.write("          }\r\n");
      out.write("      });\r\n");
      out.write("      \r\n");
      out.write("      // plan id 리스트 select\r\n");
      out.write("      getPlanIdList(3);\r\n");
      out.write("   });\r\n");
      out.write("   \r\n");
      out.write("   function getPlanIdList(num) {\r\n");
      out.write("      $.ajax({\r\n");
      out.write("         url: \"/wheremasil/plan/getPlanIdList.do\",\r\n");
      out.write("         dataType: \"json\",\r\n");
      out.write("         type: \"POST\",\r\n");
      out.write("            timeout : 30000,\r\n");
      out.write("            data : {\"num\" : num},\r\n");
      out.write("         success: function(data) {\r\n");
      out.write("            var planIdList = [];\r\n");
      out.write("            for (var idx = 0; idx < data.length; idx++) {\r\n");
      out.write("               planIdList[idx] = data[idx].planId;\r\n");
      out.write("            }\r\n");
      out.write("            getPlanMapList(planIdList, \"plan_map_\", \"main_map\");// {'L000','L001',...}, map parent id=\"plan_map_1~\", map class=\"main_map\"\r\n");
      out.write("         }// end of success(getPlanIdList)\r\n");
      out.write("      });// end of getPlanIdList(ajax)\r\n");
      out.write("   }\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"section\">\r\n");
      out.write("   <div class=\"main_center\" >\r\n");
      out.write("      <p style=\"text-align: center\">\r\n");
      out.write("         <font size=\"200%\" color=\"white\"><b>Where are you going ?</b></font>\r\n");
      out.write("      </p>\r\n");
      out.write("\r\n");
      out.write("      <div style=\"text-align: center\">\r\n");
      out.write("         <h4>\r\n");
      out.write("            <font color=\"white\">지금 당장! 어디 마실 나가고 싶다면?</font>\r\n");
      out.write("         </h4>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div style=\"position: absolute; left: 48%; top: 58%; width: 200px; height: 60px; overflow: hidden; margin-left: -50px; margin-top: -30px\">\r\n");
      out.write("         <input type=\"button\" class=\"btn btn-warning btn-lg\" value=\"START\" onclick=\"fn_layer_popup()\">\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("\r\n");
      out.write("   <video id=\"videobcg\" preload=\"auto\" autoplay=\"true\" loop=\"loop\" muted=\"muted\">\r\n");
      out.write("      <source src=\"https://a0.muscache.com/airbnb/static/Seoul-P1-4.mp4\"\r\n");
      out.write("         type=\"video/mp4\">\r\n");
      out.write("      <source src=\"https://a0.muscache.com/airbnb/static/Seoul-P1-4.webm\"\r\n");
      out.write("         type=\"video/webm\">\r\n");
      out.write("      Sorry, your browser does not support HTML5 video.\r\n");
      out.write("   </video>\r\n");
      out.write("\r\n");
      out.write("   <div style=\"position:absolute;width:1200px;top:92%;left:25%;padding:0 0;margin:0 0;\">\r\n");
      out.write("      <div style=\"margin-bottom:30px\">\r\n");
      out.write("\t      <font size=\"2\">\r\n");
      out.write("\t         <h3>최신 플랜</h3>\r\n");
      out.write("\t      </font>\r\n");
      out.write("   \t  </div>\r\n");
      out.write("      <div class=\"col-xs-6 col-md-3\" style=\"float:left;width:300px;height:220px;margin:0 20px;\">\r\n");
      out.write("        <a href=\"#\" id=\"plan_map_1\" class=\"thumbnail\" style=\"width:100%;height:100%;\">\r\n");
      out.write("          <img src=\"/wheremasil/uploads/images/default/img_not_found.png\" alt=\"...\">\r\n");
      out.write("        </a>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("      <div class=\"col-xs-6 col-md-3\" style=\"float:left;width:300px;height:220px;margin:0 20px;\">\r\n");
      out.write("        <a href=\"#\" id=\"plan_map_2\" class=\"thumbnail\" style=\"width:100%;height:100%;\">\r\n");
      out.write("          <img src=\"/wheremasil/uploads/images/default/img_not_found.png\" alt=\"...\">\r\n");
      out.write("        </a>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("      <div class=\"col-xs-6 col-md-3\" style=\"float:left;width:300px;height:220px;margin:0 20px;\">\r\n");
      out.write("        <a href=\"#\" id=\"plan_map_3\" class=\"thumbnail\" style=\"width:100%;height:100%;\">\r\n");
      out.write("          <img src=\"/wheremasil/uploads/images/default/img_not_found.png\" alt=\"...\">\r\n");
      out.write("        </a>\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("   \r\n");
      out.write("</div>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /WEB-INF/view/body/main.jsp(10,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ not empty requestScope.plan }", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("      alert(\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ requestScope.plan.title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write(" 등록 완료\");\r\n");
        out.write("   ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent(null);
    // /WEB-INF/view/body/main.jsp(13,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ not empty requestScope.session }", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("   \t  alert(\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.session}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("\");\r\n");
        out.write("   ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }
}
