/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.62
 * Generated at: 2015-06-16 02:48:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.layout;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class right_005fside_005fmenu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <title>jQuery UI Tabs - Collapse content</title>\r\n");
      out.write("\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"//code.jquery.com/ui/1.11.4/themes/black-tie/jquery-ui.css\">\r\n");
      out.write("  <script src=\"//code.jquery.com/ui/1.11.4/jquery-ui.js\"></script>\r\n");
      out.write("  \r\n");
      out.write("  <script>\r\n");
      out.write("     var dayAllCount=0; //총 여행 날짜\r\n");
      out.write("     var dayCount=1; // 현재 day\r\n");
      out.write("      var courseCount=[];\r\n");
      out.write("     \r\n");
      out.write("      function setSchedule(html, areaId) {\r\n");
      out.write("       $(\"#tab\" + dayCount + \" #tabs-1\").append('<fieldset><legend>Course'+courseCount[dayCount-1]+'</legend><table id=\"areaList\"><tr>'+\r\n");
      out.write("                       '<td>' + html +'</td></tr></table></fieldset>');\r\n");
      out.write("\r\n");
      out.write("       $(\"#tab\" + dayCount + \" #tabs-2\").append(\r\n");
      out.write("             \"<fieldset><legend>Course\"+courseCount[dayCount-1]+\"</legend>\" + \"<input type='hidden' name='scheduleList:\"+dayCount+\",costList:\"+courseCount[dayCount-1]+\",areaId' value='\" + areaId + \"'>\" + \"<table>\" +\r\n");
      out.write("             \"<tr><td>식비</td><td style='padding-left:6px'><input type='number' name='scheduleList:\"+dayCount+\",costList:\"+courseCount[dayCount-1]+\",costFood' value='0' size='9'></td></tr>\"+\r\n");
      out.write("            \"<tr><td>교통</td><td style='padding-left:6px'><input type='number' name='scheduleList:\"+dayCount+\",costList:\"+courseCount[dayCount-1]+\",costVehicle' value='0' size='9'></td></tr>\"+\r\n");
      out.write("            \"<tr><td>숙박</td><td style='padding-left:6px'><input type='number' name='scheduleList:\"+dayCount+\",costList:\"+courseCount[dayCount-1]+\",costStay' value='0' size='9'></td></tr>\"+\r\n");
      out.write("            \"<tr><td>기타</td><td style='padding-left:6px'><input type='number' name='scheduleList:\"+dayCount+\",costList:\"+courseCount[dayCount-1]+\",costEtc' value='0' size='9'></td></tr></table></fieldset>\");\r\n");
      out.write("      courseCount[dayCount-1]++;\r\n");
      out.write("    };\r\n");
      out.write("   \r\n");
      out.write("    // schedule = jquery 객체\r\n");
      out.write("    function removeSchedule(course) {\r\n");
      out.write("      $(\"#tab\" + dayCount + \" #tabs-1 fieldset:contains(\" + course + \")\").remove();\r\n");
      out.write("      $(\"#tab\" + dayCount + \" #tabs-2 fieldset:contains(\" + course + \")\").remove();\r\n");
      out.write("\r\n");
      out.write("\t\t// tab1 값 초기화\r\n");
      out.write("\t\tvar reCount = 1;\r\n");
      out.write("\t\t$(\"#tab\" + dayCount + \" #tabs-1 fieldset\").children(\"legend\").each(function() {\r\n");
      out.write("\t\t\t$(this).text(\"Course\" + reCount++);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t// tab2 값 초기화\r\n");
      out.write("\t\treCount = 1;\r\n");
      out.write("\t\t$(\"#tab\" + dayCount + \" #tabs-2 fieldset\").each(function() {\r\n");
      out.write("\t\t\t$(this).children(\"legend\").text(\"Course\" + reCount);\r\n");
      out.write("\t\t\t$(this).find(\"input\").each(function() {\r\n");
      out.write("\t\t\t\tvar nameSplit = $(this).attr(\"name\").split(\",\");\r\n");
      out.write("\t\t\t\tnameSplit[1] = nameSplit[1].split(\":\")[0] + \":\" + reCount;\r\n");
      out.write("\t\t\t\t$(this).attr(\"name\", nameSplit[0] + \",\" + nameSplit[1] + \",\" + nameSplit[2]);\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\treCount++;\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tcourseCount[dayCount - 1]--;\r\n");
      out.write("\t }\r\n");
      out.write("\t \r\n");
      out.write(" \t //오른쪽 탭 만들기\r\n");
      out.write("\t  $(function() {\r\n");
      out.write("\r\n");
      out.write("      dayAllCount=calDateRange(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.plan.startDate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write('"');
      out.write(',');
      out.write('"');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.plan.endDate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\")+1;\r\n");
      out.write("      day(dayCount);\r\n");
      out.write("      makeDiv(dayAllCount);\r\n");
      out.write("      \r\n");
      out.write("      $(\".tabs\").tabs({\r\n");
      out.write("            collapsible: false\r\n");
      out.write("          });\r\n");
      out.write("      \r\n");
      out.write("\t\t$(\"#schedule_form\").submit(function() {\r\n");
      out.write("\t\t\tif (schedulePath.length == 0) {\r\n");
      out.write("\t\t\t\talert(\"일정을 선택해주세요.\");\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\treturn true;\r\n");
      out.write("\t\t});\r\n");
      out.write("     });// end of function;\r\n");
      out.write("     \r\n");
      out.write("\r\n");
      out.write("     function makeDiv(dayAllCount){\r\n");
      out.write("          for(var i=1;i<=dayAllCount;i++){\r\n");
      out.write("           courseCount[i-1]=1;\r\n");
      out.write("           var display=\"display:none;\";\r\n");
      out.write("           if (i == 1) {\r\n");
      out.write("              display=\"display:block;\";\r\n");
      out.write("           }\r\n");
      out.write("            $(\"#rightContent\").append('<div class=\"tabs\" id=\"tab'+i+'\"style=\"'+display+'\">'+\r\n");
      out.write("            '<ul><li><a href=\"#tabs-1\">일정</a></li><li><a href=\"#tabs-2\">비용</a></li><li><a href=\"#tabs-3\">메모</a></li></ul>'+\r\n");
      out.write("             '<div id=\"tabs-1\"></div>'+\r\n");
      out.write("             '<div id=\"tabs-2\"></div>'+\r\n");
      out.write("            '<div id=\"tabs-3\"><table border=\"1\">'+\r\n");
      out.write("                 '<textarea name=\"scheduleList:'+i+',costList:0,memo\" style=\"margin: 0px; height: 540px; width: 221px; overflow:auto;\" wrap=\"hard\" >메모를 해주세요.</textarea>'+\r\n");
      out.write("               '</table></div></div>');\r\n");
      out.write("          }\r\n");
      out.write("          \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("   /*\r\n");
      out.write("     * 두 날짜의 차이를 일자로 구한다.(조회 종료일 - 조회 시작일)\r\n");
      out.write("     * @return 기간에 해당하는 일자\r\n");
      out.write("     */\r\n");
      out.write("    function calDateRange(val1, val2)\r\n");
      out.write("    {\r\n");
      out.write("      var stYear = val1.substring(0,4);\r\n");
      out.write("      var stMonth = val1.substring(4,6);\r\n");
      out.write("      var stDay= val1.substring(6,8);\r\n");
      out.write("      \r\n");
      out.write("      var endYear = val2.substring(0,4);\r\n");
      out.write("      var endMonth = val2.substring(4,6);\r\n");
      out.write("      var endDay= val2.substring(6,8);\r\n");
      out.write("\r\n");
      out.write("        // 월 - 1(자바스크립트는 월이 0부터 시작하기 때문에...)\r\n");
      out.write("        // Number()를 이용하여 08, 09월을 10진수로 인식하게 함.\r\n");
      out.write("        stMonth = (Number(stMonth) - 1) + \"\";\r\n");
      out.write("        endMonth = (Number(endMonth) - 1) + \"\";\r\n");
      out.write("\r\n");
      out.write("        var fromDate = new Date(stYear, stMonth, stDay);\r\n");
      out.write("        var toDate = new Date(endYear, endMonth, endDay);\r\n");
      out.write("       var date = (toDate.getTime() - fromDate.getTime()) / 1000 / 60 / 60 / 24;\r\n");
      out.write("        return date;\r\n");
      out.write("    }\r\n");
      out.write("   \r\n");
      out.write("   // day 다음 버튼 누른 후의 작업.\r\n");
      out.write("   function afterDayCheck(){\r\n");
      out.write("      if(dayCount < dayAllCount){\r\n");
      out.write("         $(\"#tab\"+dayCount).hide();\r\n");
      out.write("         dayCount++;\r\n");
      out.write("         $(\"#tab\"+dayCount).show();\r\n");
      out.write("         \r\n");
      out.write("      }else if(dayCount==dayAllCount){\r\n");
      out.write("         alert(\"마지막 페이지입니다.\");\r\n");
      out.write("      }\r\n");
      out.write("         day(dayCount);\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   // day 이전 버튼 누른 후의 작업.\r\n");
      out.write("   function beforeDayCheck(){\r\n");
      out.write("      if(1<dayCount){\r\n");
      out.write("         $(\"#tab\"+dayCount).hide();\r\n");
      out.write("         dayCount--;\r\n");
      out.write("         $(\"#tab\"+dayCount).show();\r\n");
      out.write("      }else if(dayCount==1){\r\n");
      out.write("         alert(\"첫번째 페이지입니다.\");\r\n");
      out.write("      }\r\n");
      out.write("         day(dayCount);\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   // 화면에 현재day 출력.\r\n");
      out.write("   function day(dayCount) {\r\n");
      out.write("      $(\"#day\").html(\"<h2 align='center'>DAY\"+dayCount+\"</h2>\");\r\n");
      out.write("   }\r\n");
      out.write("\r\n");
      out.write(" </script>\r\n");
      out.write("\r\n");
      out.write("<input type=\"button\" class=\"img_button_before\" name=\"before\" onclick=\"beforeDayCheck()\" style=\"float:left;\"><input type=\"button\"  class=\"img_button_next\" name=\"after\" onclick=\"afterDayCheck()\" style=\"float:right;\"><div id=\"day\"></div>\r\n");
      out.write("\r\n");
      out.write("<form id=\"schedule_form\" method=\"post\" action=\"/wheremasil/plan/session/planInfo.do\">\r\n");
      out.write("\r\n");
      out.write("   <div id=\"rightContent\"></div>\r\n");
      out.write("   <input type=\"hidden\" name=\"title\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.plan.title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("   <input type=\"hidden\" name=\"theme\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.plan.theme }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("   <input type=\"hidden\" name=\"groupNum\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.plan.groupNum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("   <input type=\"hidden\" name=\"startDate\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.plan.startDate }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("   <input type=\"hidden\" name=\"endDate\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.plan.endDate }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("   <input type=\"submit\" class=\"submit_plan\" value=\"Planner 완성\" style=\"width:320px;\">\r\n");
      out.write("  </form>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
