/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.62
 * Generated at: 2015-06-17 00:31:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.layout;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class template_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/wheremasil/script/jquery.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/wheremasil/script/map_view.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Latest compiled and minified CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Optional theme -->\r\n");
      out.write("<link href=\"https://maxcdn.bootstrapcdn.com/bootswatch/3.3.4/cosmo/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<!-- Latest compiled and minified JavaScript -->\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- pace : 프로그레스바 lib -->\r\n");
      out.write("<script data-pace-options='{ \"document\": false, \"ajax\": true, \"eventLag\": false }' src=\"/wheremasil/script/pace.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/wheremasil/css/pace/orange/pace-theme-center-atom.css\" />\r\n");
      out.write("\r\n");
      out.write("<!-- SearchCSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/wheremasil/css/search/search.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- mypage CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/wheremasil/css/member/mypage.css\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("header {\r\n");
      out.write("\ttext-align: left;\r\n");
      out.write("\tpadding: 13px;\r\n");
      out.write("\theight:57px;\r\n");
      out.write("\tbackground-color:#4E5D6C;\r\n");
      out.write("}\r\n");
      out.write("body {\r\n");
      out.write("\r\n");
      out.write("\tbackground-color: #ffffff;\r\n");
      out.write("}\r\n");
      out.write(".left_nav {\r\n");
      out.write("\tline-height: 50px; /*줄 간격 - 메뉴이므로 줄간격을 넓게*/\r\n");
      out.write("\tbackground-color: #FFFFFF;\r\n");
      out.write("\twidth:18%;\r\n");
      out.write("\tmargin-top: 5px;\r\n");
      out.write("\tmargin-bottom: 5px;\r\n");
      out.write("\toverflow-y:scroll;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("}\r\n");
      out.write(".right_nav {\r\n");
      out.write("\tline-height: 50px; /*줄 간격 - 메뉴이므로 줄간격을 넓게*/\r\n");
      out.write("\tbackground-color: #FFFFFF;\r\n");
      out.write("\twidth:18%;\r\n");
      out.write("\tmargin-top: 5px;\r\n");
      out.write("\tmargin-bottom: 5px;\r\n");
      out.write("\tmargin-right: 0px;\r\n");
      out.write("\tmargin-left: 0px;\r\n");
      out.write("\tpadding:0px;\r\n");
      out.write("\toverflow-y:scroll;\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("}\r\n");
      out.write("section {\r\n");
      out.write("\t/*TODO : 페이지를 줄이면 밑으로 내려간다.. 어떻게?*/\r\n");
      out.write("\tpadding-top: 5px;\r\n");
      out.write("\tpadding-bottom: 5px;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("}\r\n");
      out.write("footer {\r\n");
      out.write(" \tpadding-top: 20px;\r\n");
      out.write("\tbackground-color: #222222;\r\n");
      out.write("\tcolor: gray;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tclear: both;\r\n");
      out.write("\tmargin-right: 0px;\r\n");
      out.write("\tmargin-left: 0px;\r\n");
      out.write("\tpadding-right:0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#videobcg { \r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: -200px;\r\n");
      out.write("\tleft: 0px;\r\n");
      out.write("\tmin-width: 100%;\r\n");
      out.write("\tmin-height:840px;\r\n");
      out.write("\twidth: auto;\r\n");
      out.write("\theight: auto;\r\n");
      out.write("\tz-index: -1;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("}\r\n");
      out.write(".main_center { position:absolute; top:70%; left:50%; width:40%; height:30%; overflow:hidden; margin-top:-15%; margin-left:-20%;}\r\n");
      out.write("h1 {\r\n");
      out.write("    text-transform: uppercase;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    color: #666;\r\n");
      out.write("    margin: 0 0 30px 0;\r\n");
      out.write("    letter-spacing: 4px;\r\n");
      out.write("    font: normal 26px/1 Verdana, Helvetica;\r\n");
      out.write("    position: relative;\r\n");
      out.write("}\r\n");
      out.write("h1:after, \r\n");
      out.write("h1:before {\r\n");
      out.write("    background-color: #777;\r\n");
      out.write("    content: \"\";\r\n");
      out.write("    height: 1px;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 15px;\r\n");
      out.write("    width: 120px;   \r\n");
      out.write("}\r\n");
      out.write("h1:after {      \r\n");
      out.write("    right: 0;\r\n");
      out.write("}\r\n");
      out.write("h1:before {\r\n");
      out.write("    background-image: linear-gradient(right, #777, #fff);\r\n");
      out.write("    left: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".main_button {\r\n");
      out.write("   border: 1px solid #0a3c59;\r\n");
      out.write("   outline: 0;\r\n");
      out.write("   background: #3e3e3e;\r\n");
      out.write("   background: -webkit-gradient(linear, left top, left bottom, from(#ffffff), to(#3e3e3e));\r\n");
      out.write("   background: -webkit-linear-gradient(top, #ffffff, #3e3e3e);\r\n");
      out.write("   background: -moz-linear-gradient(top, #ffffff, #3e3e3e);\r\n");
      out.write("   background: -ms-linear-gradient(top, #ffffff, #3e3e3e);\r\n");
      out.write("   background: -o-linear-gradient(top, #ffffff, #3e3e3e);\r\n");
      out.write("   background-image: -ms-linear-gradient(top, #ffffff 0%, #3e3e3e 100%);\r\n");
      out.write("   padding: 7.5px 15px;\r\n");
      out.write("   -webkit-border-radius: 30px;\r\n");
      out.write("   -moz-border-radius: 30px;\r\n");
      out.write("   border-radius: 30px;\r\n");
      out.write("   -webkit-box-shadow: rgba(255,255,255,0.4) 0 0px 0, inset rgba(255,255,255,0.4) 0 1px 0;\r\n");
      out.write("   -moz-box-shadow: rgba(255,255,255,0.4) 0 0px 0, inset rgba(255,255,255,0.4) 0 1px 0;\r\n");
      out.write("   box-shadow: rgba(255,255,255,0.4) 0 0px 0, inset rgba(255,255,255,0.4) 0 1px 0;\r\n");
      out.write("   text-shadow: #7ea4bd 0 1px 0;\r\n");
      out.write("   color: #ffffff;\r\n");
      out.write("   font-size: 13px;\r\n");
      out.write("   font-family: helvetica, serif;\r\n");
      out.write("   text-decoration: none;\r\n");
      out.write("   vertical-align: middle;\r\n");
      out.write("   }\r\n");
      out.write(".main_button:hover {\r\n");
      out.write("   border: 1px solid #0a3c59;\r\n");
      out.write("   outline: 0;\r\n");
      out.write("   text-shadow: #1e4158 0 1px 0;\r\n");
      out.write("   background: #3e3e3e;\r\n");
      out.write("   background: -webkit-gradient(linear, left top, left bottom, from(#ffffff), to(#3e3e3e));\r\n");
      out.write("   background: -webkit-linear-gradient(top, #ffffff, #3e3e3e);\r\n");
      out.write("   background: -moz-linear-gradient(top, #ffffff, #3e3e3e);\r\n");
      out.write("   background: -ms-linear-gradient(top, #ffffff, #3e3e3e);\r\n");
      out.write("   background: -o-linear-gradient(top, #ffffff, #3e3e3e);\r\n");
      out.write("   background-image: -ms-linear-gradient(top, #ffffff 0%, #3e3e3e 100%);\r\n");
      out.write("   color: #fff;\r\n");
      out.write("   }\r\n");
      out.write(".main_button:active {\r\n");
      out.write("   outline: 0;\r\n");
      out.write("   text-shadow: #1e4158 0 1px 0;\r\n");
      out.write("   border: 1px solid #0a3c59;\r\n");
      out.write("   background: #ffffff;\r\n");
      out.write("   background: -webkit-gradient(linear, left top, left bottom, from(#3e3e3e), to(#3e3e3e));\r\n");
      out.write("   background: -webkit-linear-gradient(top, #3e3e3e, #ffffff);\r\n");
      out.write("   background: -moz-linear-gradient(top, #3e3e3e, #ffffff);\r\n");
      out.write("   background: -ms-linear-gradient(top, #3e3e3e, #ffffff);\r\n");
      out.write("   background: -o-linear-gradient(top, #3e3e3e, #ffffff);\r\n");
      out.write("   background-image: -ms-linear-gradient(top, #3e3e3e 0%, #ffffff 100%);\r\n");
      out.write("   color: #fff;\r\n");
      out.write("}\r\n");
      out.write(".plan_button {\r\n");
      out.write("   outline: 0;\r\n");
      out.write("   border: 0px solid #0a3c59;\r\n");
      out.write("   background: #a8a8a8;\r\n");
      out.write("   background: -webkit-gradient(linear, left top, left bottom, from(#ffffff), to(#a8a8a8));\r\n");
      out.write("   background: -webkit-linear-gradient(top, #ffffff, #a8a8a8);\r\n");
      out.write("   background: -moz-linear-gradient(top, #ffffff, #a8a8a8);\r\n");
      out.write("   background: -ms-linear-gradient(top, #ffffff, #a8a8a8);\r\n");
      out.write("   background: -o-linear-gradient(top, #ffffff, #a8a8a8);\r\n");
      out.write("   background-image: -ms-linear-gradient(top, #ffffff 0%, #a8a8a8 100%);\r\n");
      out.write("   padding: 8.5px 17px;\r\n");
      out.write("   -webkit-border-radius: 7px;\r\n");
      out.write("   -moz-border-radius: 7px;\r\n");
      out.write("   border-radius: 7px;\r\n");
      out.write("   -webkit-box-shadow: rgba(255,255,255,0.4) 0 0px 0, inset rgba(255,255,255,0.4) 0 0px 0;\r\n");
      out.write("   -moz-box-shadow: rgba(255,255,255,0.4) 0 0px 0, inset rgba(255,255,255,0.4) 0 0px 0;\r\n");
      out.write("   box-shadow: rgba(255,255,255,0.4) 0 0px 0, inset rgba(255,255,255,0.4) 0 0px 0;\r\n");
      out.write("   text-shadow: #9c9c9c 0 1px 0;\r\n");
      out.write("   color: #575757;\r\n");
      out.write("   font-size: 12px;\r\n");
      out.write("   font-family: helvetica, serif;\r\n");
      out.write("   text-decoration: none;\r\n");
      out.write("   vertical-align: middle;\r\n");
      out.write("   width: 100%;\r\n");
      out.write("   height: 20px;\r\n");
      out.write("   }\r\n");
      out.write(".plan_button:hover {\r\n");
      out.write("   outline: 0;\r\n");
      out.write("   border: 0px solid #0a3c59;\r\n");
      out.write("   text-shadow: #575757 0 1px 0;\r\n");
      out.write("   background: #a8a8a8;\r\n");
      out.write("   background: -webkit-gradient(linear, left top, left bottom, from(#ffffff), to(#a8a8a8));\r\n");
      out.write("   background: -webkit-linear-gradient(top, #ffffff, #a8a8a8);\r\n");
      out.write("   background: -moz-linear-gradient(top, #ffffff, #a8a8a8);\r\n");
      out.write("   background: -ms-linear-gradient(top, #ffffff, #a8a8a8);\r\n");
      out.write("   background: -o-linear-gradient(top, #ffffff, #a8a8a8);\r\n");
      out.write("   background-image: -ms-linear-gradient(top, #ffffff 0%, #a8a8a8 100%);\r\n");
      out.write("   color: #575757;\r\n");
      out.write("   }\r\n");
      out.write(".plan_button:active {\r\n");
      out.write("   outline: 0;\r\n");
      out.write("   text-shadow: #575757 0 1px 0;\r\n");
      out.write("   border: 0px solid #0a3c59;\r\n");
      out.write("   background: #ffffff;\r\n");
      out.write("   background: -webkit-gradient(linear, left top, left bottom, from(#a8a8a8), to(#a8a8a8));\r\n");
      out.write("   background: -webkit-linear-gradient(top, #a8a8a8, #ffffff);\r\n");
      out.write("   background: -moz-linear-gradient(top, #a8a8a8, #ffffff);\r\n");
      out.write("   background: -ms-linear-gradient(top, #a8a8a8, #ffffff);\r\n");
      out.write("   background: -o-linear-gradient(top, #a8a8a8, #ffffff);\r\n");
      out.write("   background-image: -ms-linear-gradient(top, #a8a8a8 0%, #ffffff 100%);\r\n");
      out.write("   color: #575757;\r\n");
      out.write("}\r\n");
      out.write(".close-thik:after {\r\n");
      out.write("  color: #777;\r\n");
      out.write("  font: 14px/100% arial, sans-serif;\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  right: 5px;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  text-shadow: 0 1px 0 #fff;\r\n");
      out.write("  top: 5px;\r\n");
      out.write("  content: '✖'; /* UTF-8 symbol */\r\n");
      out.write("}\r\n");
      out.write(".schedule_close-thik:after {\r\n");
      out.write("  position:relative;\r\n");
      out.write("  left: 100%;\r\n");
      out.write("  top: 0px;\r\n");
      out.write("  right: 0px;\r\n");
      out.write("  bottom: 0px;\r\n");
      out.write("  color: #777;\r\n");
      out.write("  font: 14px/100% arial, sans-serif;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  text-shadow: 0 1px 0 #fff;\r\n");
      out.write("  content: '✖'; /* UTF-8 symbol */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".infoview_container {\r\n");
      out.write("\twidth:96%;\r\n");
      out.write("\tpadding:2%;\r\n");
      out.write("\tborder: 1px solid #0a3c59;\r\n");
      out.write("\toverflow-y:hidden;\r\n");
      out.write("\tclear:both;\r\n");
      out.write("}\r\n");
      out.write(".infoview_image_block {\r\n");
      out.write("\twidth:34%;\r\n");
      out.write("\tfloat:left;\r\n");
      out.write("\tdisplay:-webkit-box;\r\n");
      out.write("\t-webkit-box-pack:center;\r\n");
      out.write("\t-webkit-box-align:center;\r\n");
      out.write("}\r\n");
      out.write(".infoview_image {\r\n");
      out.write("\twidth:70px;\r\n");
      out.write("\theight:70px;\r\n");
      out.write("\tmargin-top:15px;\r\n");
      out.write("}\t\r\n");
      out.write(".infoview_text_block {\r\n");
      out.write("\twidth:66%;\r\n");
      out.write("\tmin-height:inherit;\r\n");
      out.write("\tmax-height:inherit;\r\n");
      out.write("\ttext-align:center;\r\n");
      out.write("\tfloat:right;\r\n");
      out.write("}\r\n");
      out.write(".infoview_text_title {\r\n");
      out.write("\twidth:100%;\r\n");
      out.write("\theight:0px;\r\n");
      out.write("\tmargin:0 auto;\r\n");
      out.write("\tfont-size:90%;\r\n");
      out.write("\twhite-space:nowrap;\r\n");
      out.write("}\r\n");
      out.write(".infoview_text_content {\r\n");
      out.write("\twidth:100%;\r\n");
      out.write("\tpadding-top:20%;\r\n");
      out.write("\tline-height:120%;\r\n");
      out.write("\tfont-size:80%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".borderme {\r\n");
      out.write("\tborder:none;\r\n");
      out.write("}\r\n");
      out.write(".borderme:hover {\r\n");
      out.write("\tborder:#ff0000 solid 1px;\r\n");
      out.write("}\r\n");
      out.write(".schedule_borderme {\r\n");
      out.write("\tborder:none;\r\n");
      out.write("\t-webkit-filter: blur(0px);\r\n");
      out.write("}\r\n");
      out.write(".schedule_borderme:hover {\r\n");
      out.write("\tborder:#ff0000 solid 1px;\r\n");
      out.write("\t-webkit-filter: blur(1px);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".map_wrap, .map_wrap * {margin:0;padding:0;font-family:'Malgun Gothic',dotum,'돋움',sans-serif;font-size:12px;}\r\n");
      out.write(".map_wrap a, .map_wrap a:hover, .map_wrap a:active{color:#000;text-decoration: none;}\r\n");
      out.write(".map_wrap {position:relative;width:100%;height:500px;}\r\n");
      out.write("#menu_wrap {position:absolute;top:0;left:0;bottom:0;width:260px;max-height:500px;margin:10px 0 30px 10px;padding:5px;overflow-y:auto;background:rgba(255, 255, 255, 0.7);z-index: 1;font-size:12px;border-radius: 10px;}\r\n");
      out.write(".bg_white {background:#fff;}\r\n");
      out.write("#menu_wrap hr {display: block; height: 1px;border: 0; border-top: 2px solid #5F5F5F;margin:3px 0;}\r\n");
      out.write("#menu_wrap .option{text-align: center;}\r\n");
      out.write("#menu_wrap .option p {margin:10px 0;}  \r\n");
      out.write("#menu_wrap .option button {margin-left:5px;}\r\n");
      out.write("#placesList li {list-style: none;}\r\n");
      out.write("#placesList .item {position:relative;border-bottom:1px solid #888;overflow: hidden;cursor: pointer;min-height: 65px;}\r\n");
      out.write("#placesList .item span {display: block;margin-top:4px;}\r\n");
      out.write("#placesList .item h5, #placesList .item .info {text-overflow: ellipsis;overflow: hidden;white-space: nowrap;}\r\n");
      out.write("#placesList .item .info{padding:10px 0 10px 55px;}\r\n");
      out.write("#placesList .info .gray {color:#8a8a8a;}\r\n");
      out.write("#placesList .info .jibun {padding-left:26px;background:url(http://i1.daumcdn.net/localimg/localimages/07/mapapidoc/places_jibun.png) no-repeat;}\r\n");
      out.write("#placesList .info .tel {color:#009900;}\r\n");
      out.write("#placesList .item .markerbg {float:left;position:absolute;width:36px; height:37px;margin:10px 0 0 10px;background:url(http://i1.daumcdn.net/localimg/localimages/07/mapapidoc/marker_number_blue.png) no-repeat;}\r\n");
      out.write("#placesList .item .marker_1 {background-position: 0 -10px;}\r\n");
      out.write("#placesList .item .marker_2 {background-position: 0 -56px;}\r\n");
      out.write("#placesList .item .marker_3 {background-position: 0 -102px}\r\n");
      out.write("#placesList .item .marker_4 {background-position: 0 -148px;}\r\n");
      out.write("#placesList .item .marker_5 {background-position: 0 -194px;}\r\n");
      out.write("#placesList .item .marker_6 {background-position: 0 -240px;}\r\n");
      out.write("#placesList .item .marker_7 {background-position: 0 -286px;}\r\n");
      out.write("#placesList .item .marker_8 {background-position: 0 -332px;}\r\n");
      out.write("#placesList .item .marker_9 {background-position: 0 -378px;}\r\n");
      out.write("#placesList .item .marker_10 {background-position: 0 -423px;}\r\n");
      out.write("#placesList .item .marker_11 {background-position: 0 -470px;}\r\n");
      out.write("#placesList .item .marker_12 {background-position: 0 -516px;}\r\n");
      out.write("#placesList .item .marker_13 {background-position: 0 -562px;}\r\n");
      out.write("#placesList .item .marker_14 {background-position: 0 -608px;}\r\n");
      out.write("#placesList .item .marker_15 {background-position: 0 -654px;}\r\n");
      out.write("#pagination {margin:10px auto;text-align: center;height:18px}\r\n");
      out.write("#pagination a {display:inline-block;margin-right:10px;}\r\n");
      out.write("#pagination .on {font-weight: bold; cursor: default;color:#777;}\r\n");
      out.write("\r\n");
      out.write("input.img_button_before {\r\n");
      out.write("       background: url(/wheremasil/uploads/images/icon/Last_Track_Left_Arrow_32.png) no-repeat;\r\n");
      out.write("       border: none;\r\n");
      out.write("       width: 32px;\r\n");
      out.write("       height: 32px;\r\n");
      out.write("       margin-left:20px;\r\n");
      out.write("       margin-top:20px;\r\n");
      out.write("       cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("input.img_button_next {\r\n");
      out.write("       background: url(/wheremasil/uploads/images/icon/Skip_Track_32.png) no-repeat;\r\n");
      out.write("       border: none;\r\n");
      out.write("       width: 32px;\r\n");
      out.write("       height: 32px;\r\n");
      out.write("       margin-right:20px;\r\n");
      out.write("       margin-top:20px;\r\n");
      out.write("       cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("input.submit_plan {\r\n");
      out.write("\t   background-color: #FFC107;\r\n");
      out.write("       border: none;\r\n");
      out.write("       width: auto;\r\n");
      out.write("       height: auto;\r\n");
      out.write("       cursor: pointer;\r\n");
      out.write("       font-variant:small-caps;\r\n");
      out.write("       font-weight:bold;\r\n");
      out.write("       font-size:25px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("input.img_button_login {\r\n");
      out.write("       background: url(/wheremasil/uploads/images/icon/login_btn.png) no-repeat;\r\n");
      out.write("\t   float:right;\r\n");
      out.write("\t   height: 121px;\r\n");
      out.write("\t   width: 50px;\r\n");
      out.write("\t   border: 0px;\r\n");
      out.write("\t   border-radius:7px;\r\n");
      out.write("\t   color:white;\r\n");
      out.write("\t   font-size:22px;\r\n");
      out.write("}\r\n");
      out.write(".schedule_container {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 750px;\r\n");
      out.write("\tmargin: 0 0 auto;\r\n");
      out.write("\tpadding: 0 0 auto;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tbackground-color: #FFFFFF;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".schedule_container .itembox {\r\n");
      out.write("\twidth: 1424px;\r\n");
      out.write("\theight: inherit;\r\n");
      out.write("\tmargin: 0 auto;\r\n");
      out.write("\tpadding: 0 auto;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".schedule_container .side {\r\n");
      out.write("\twidth: 470px;\r\n");
      out.write("\theight: inherit;\r\n");
      out.write("\tmargin: 0 auto;\r\n");
      out.write("\tpadding: 0 auto;\r\n");
      out.write("\tborder-left: 1px solid black;\r\n");
      out.write("\t\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".schedule_container .side .map {\r\n");
      out.write("\twidth: 380px;\r\n");
      out.write("\theight: 380px;\r\n");
      out.write("\tmargin: 20px 45px;\r\n");
      out.write("\tpadding: 0 auto;\r\n");
      out.write("\tborder: 1px solid black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".schedule_container .side .cost {\r\n");
      out.write("\twidth: 350px;\r\n");
      out.write("\theight: 310px;\r\n");
      out.write("\tmargin: 10px 60px;\r\n");
      out.write("\tpadding: 0 auto;\r\n");
      out.write("\tborder:0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".schedule_container .itembox .root {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\twidth: 1144px;\r\n");
      out.write("\theight: 560px;\r\n");
      out.write("\tmargin-top: 30px;\r\n");
      out.write("\tmargin-bottom: 50px;\r\n");
      out.write("\tmargin-left: 130px;\r\n");
      out.write("\tmargin-right: 130px;\r\n");
      out.write("\tpadding-top: 50px;\r\n");
      out.write("\tpadding-left: 50px;\r\n");
      out.write("\tpadding-right: 50px;\r\n");
      out.write("\toverflow-x: hidden;\r\n");
      out.write("\t\r\n");
      out.write("\t-webkit-box-shadow: 5px 5px 30px #D3D3D3;\r\n");
      out.write("\t-moz-box-shadow: 5px 5px 30px #D3D3D3;\r\n");
      out.write("\tbox-shadow: 5px 5px 30px #D3D3D3;\r\n");
      out.write("\tbackground-image: -moz-linear-gradient(top, #FFFFFF, #D3D3D3);\r\n");
      out.write("\tbackground-image: -webkit-gradient(linear, left top, left bottom, color-stop(0.00, #FFFFFF), color-stop(1.0, #D3D3D3));\r\n");
      out.write("\tbackground-color: #DDDDDD;\r\n");
      out.write("\tfont-family: Verdana, Geneva, sans-serif;\r\n");
      out.write("\tfont-size: 12pt;\r\n");
      out.write("\tcolor: #888888;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".schedule_container .itembox .day {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\twidth: 300px;\r\n");
      out.write("\theight: 460px;\r\n");
      out.write("\tmargin: 0 auto;\r\n");
      out.write("\tpadding: 0 auto;\r\n");
      out.write("\toverflow-y: auto;\r\n");
      out.write("\t\r\n");
      out.write("\t-webkit-border-radius: 10px;\r\n");
      out.write("\t-moz-border-radius: 10px;\r\n");
      out.write("\tborder-radius: 10px;\r\n");
      out.write("\t-webkit-box-shadow: 5px 5px 30px #D3D3D3;\r\n");
      out.write("\t-moz-box-shadow: 5px 5px 30px #D3D3D3;\r\n");
      out.write("\tbox-shadow: 5px 5px 30px #D3D3D3;\r\n");
      out.write("\tbackground-color: #FFF;\r\n");
      out.write("\tfont-family: Verdana, Geneva, sans-serif;\r\n");
      out.write("\tfont-size: 12pt;\r\n");
      out.write("\tcolor: #888888;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".slide_prev {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tleft: 35px;\r\n");
      out.write("\ttop: 400px;\r\n");
      out.write("\tbackground: url(/wheremasil/uploads/images/icon/Last_Track_Left_Arrow_64.png) no-repeat;\r\n");
      out.write("    border: none;\r\n");
      out.write("    width: 64px;\r\n");
      out.write("    height: 64px;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".slide_next {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tleft: 1310px;\r\n");
      out.write("\ttop: 400px;\r\n");
      out.write("    background: url(/wheremasil/uploads/images/icon/Skip_Track_64.png) no-repeat;\r\n");
      out.write("    border: none;\r\n");
      out.write("    width: 64px;\r\n");
      out.write("    height: 64px;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".main_map {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\tmargin: 0 0;\r\n");
      out.write("\tpadding: 0 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".abody\r\n");
      out.write("{   position:absolute; \r\n");
      out.write("\ttop:95%;\r\n");
      out.write("\tdisplay:none;\r\n");
      out.write("\twidth:1880px;\r\n");
      out.write("\tfloat:left;\r\n");
      out.write("}\r\n");
      out.write(".mapImg\r\n");
      out.write("{\r\n");
      out.write("\twidth:150px;\r\n");
      out.write("\theight:300px;\r\n");
      out.write("\tbackground-color:#FFF;\r\n");
      out.write("\t\r\n");
      out.write("\tfloat:left;\r\n");
      out.write("\tmargin:30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table.type08 {\r\n");
      out.write("    border-collapse: collapse;\r\n");
      out.write("    text-align: left;\r\n");
      out.write("    line-height: 1.5;\r\n");
      out.write("    border-left: 1px solid #ccc;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table.type08 thead th {\r\n");
      out.write("    padding: 10px;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    border-top: 1px solid #ccc;\r\n");
      out.write("    border-right: 1px solid #ccc;\r\n");
      out.write("    border-bottom: 2px solid #c00;\r\n");
      out.write("    background: #dcdcd1;\r\n");
      out.write("}\r\n");
      out.write("table.type08 tbody th {\r\n");
      out.write("    width: 200px;\r\n");
      out.write("    padding: 10px;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    vertical-align: top;\r\n");
      out.write("    border-right: 1px solid #ccc;\r\n");
      out.write("    border-bottom: 1px solid #ccc;\r\n");
      out.write("    background: #ececec;\r\n");
      out.write("}\r\n");
      out.write("table.type08 td {\r\n");
      out.write("    width: 200px;\r\n");
      out.write("    padding: 10px;\r\n");
      out.write("    vertical-align: top;\r\n");
      out.write("    border-right: 1px solid #ccc;\r\n");
      out.write("    border-bottom: 1px solid #ccc;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"tile_header\">\r\n");
      out.write("\t\t<header>\r\n");
      out.write("\t\t\t<!-- name : tiles 설정 - put- attribute 의  name 속성. -->\r\n");
      out.write("\t\t\t");
      if (_jspx_meth_tiles_005finsertAttribute_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t</header>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"tile_left_nav\" style=\"visibility:hidden\">\r\n");
      out.write("\t\t<nav class=\"left_nav\">\r\n");
      out.write("\t\t\t");
      if (_jspx_meth_tiles_005finsertAttribute_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"tile_section\">\r\n");
      out.write("\t\t<section>\r\n");
      out.write("\t\t\t");
      if (_jspx_meth_tiles_005finsertAttribute_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"tile_right_nav\" style=\"visibility:hidden\">\r\n");
      out.write("\t\t<nav class=\"right_nav\">\r\n");
      out.write("\t\t\t");
      if (_jspx_meth_tiles_005finsertAttribute_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"tile_footer\">\r\n");
      out.write("\t\t<footer>\r\n");
      out.write("\t\t\t");
      if (_jspx_meth_tiles_005finsertAttribute_005f4(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t</footer>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_tiles_005finsertAttribute_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:insertAttribute
    org.apache.tiles.jsp.taglib.InsertAttributeTag _jspx_th_tiles_005finsertAttribute_005f0 = (new org.apache.tiles.jsp.taglib.InsertAttributeTag());
    _jsp_instancemanager.newInstance(_jspx_th_tiles_005finsertAttribute_005f0);
    _jspx_th_tiles_005finsertAttribute_005f0.setJspContext(_jspx_page_context);
    // /WEB-INF/view/layout/template.jsp(549,3) name = name type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005finsertAttribute_005f0.setName("header");
    _jspx_th_tiles_005finsertAttribute_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_tiles_005finsertAttribute_005f0);
    return false;
  }

  private boolean _jspx_meth_tiles_005finsertAttribute_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:insertAttribute
    org.apache.tiles.jsp.taglib.InsertAttributeTag _jspx_th_tiles_005finsertAttribute_005f1 = (new org.apache.tiles.jsp.taglib.InsertAttributeTag());
    _jsp_instancemanager.newInstance(_jspx_th_tiles_005finsertAttribute_005f1);
    _jspx_th_tiles_005finsertAttribute_005f1.setJspContext(_jspx_page_context);
    // /WEB-INF/view/layout/template.jsp(555,3) name = name type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005finsertAttribute_005f1.setName("left_menu");
    _jspx_th_tiles_005finsertAttribute_005f1.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_tiles_005finsertAttribute_005f1);
    return false;
  }

  private boolean _jspx_meth_tiles_005finsertAttribute_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:insertAttribute
    org.apache.tiles.jsp.taglib.InsertAttributeTag _jspx_th_tiles_005finsertAttribute_005f2 = (new org.apache.tiles.jsp.taglib.InsertAttributeTag());
    _jsp_instancemanager.newInstance(_jspx_th_tiles_005finsertAttribute_005f2);
    _jspx_th_tiles_005finsertAttribute_005f2.setJspContext(_jspx_page_context);
    // /WEB-INF/view/layout/template.jsp(561,3) name = name type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005finsertAttribute_005f2.setName("body");
    _jspx_th_tiles_005finsertAttribute_005f2.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_tiles_005finsertAttribute_005f2);
    return false;
  }

  private boolean _jspx_meth_tiles_005finsertAttribute_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:insertAttribute
    org.apache.tiles.jsp.taglib.InsertAttributeTag _jspx_th_tiles_005finsertAttribute_005f3 = (new org.apache.tiles.jsp.taglib.InsertAttributeTag());
    _jsp_instancemanager.newInstance(_jspx_th_tiles_005finsertAttribute_005f3);
    _jspx_th_tiles_005finsertAttribute_005f3.setJspContext(_jspx_page_context);
    // /WEB-INF/view/layout/template.jsp(567,3) name = name type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005finsertAttribute_005f3.setName("right_menu");
    _jspx_th_tiles_005finsertAttribute_005f3.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_tiles_005finsertAttribute_005f3);
    return false;
  }

  private boolean _jspx_meth_tiles_005finsertAttribute_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:insertAttribute
    org.apache.tiles.jsp.taglib.InsertAttributeTag _jspx_th_tiles_005finsertAttribute_005f4 = (new org.apache.tiles.jsp.taglib.InsertAttributeTag());
    _jsp_instancemanager.newInstance(_jspx_th_tiles_005finsertAttribute_005f4);
    _jspx_th_tiles_005finsertAttribute_005f4.setJspContext(_jspx_page_context);
    // /WEB-INF/view/layout/template.jsp(573,3) name = name type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005finsertAttribute_005f4.setName("footer");
    _jspx_th_tiles_005finsertAttribute_005f4.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_tiles_005finsertAttribute_005f4);
    return false;
  }
}
