/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.62
 * Generated at: 2015-06-17 03:27:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.body.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class review_005fwriter_005fform_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write(" \r\n");
      out.write("    \r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<script  src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"/wheremasil/ckeditor/ckeditor.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function delay(gap) { /* gap is in millisecs */\r\n");
      out.write("    var then,now;\r\n");
      out.write("    then = new Date().getTime();\r\n");
      out.write("    now = then;\r\n");
      out.write("    while((now - then) < gap) {\r\n");
      out.write("        now = new Date().getTime();\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \t\r\n");
      out.write("    \t\r\n");
      out.write("    \t\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("function deletePost(posting_id){\r\n");
      out.write("\t//alert(posting_id);\t\r\n");
      out.write("var txt = \"posting_id\" + \"=\"+ posting_id;\r\n");
      out.write("\t\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("   \t    url: '/wheremasil/board/deletePost.do',\r\n");
      out.write("   \t type:\"post\",\r\n");
      out.write("   \t    processData: false,\r\n");
      out.write("   \t \r\n");
      out.write("\t    data:txt,\r\n");
      out.write("\t    dataType:\"text\",\r\n");
      out.write("   \t    \r\n");
      out.write("   \t    success: function(result){\r\n");
      out.write("   \t   \r\n");
      out.write("   \t    \t\r\n");
      out.write("   \t    \t//alert(\"성공\");\r\n");
      out.write("   \t    \t\r\n");
      out.write("   \t    \t\r\n");
      out.write("   \t    \t\r\n");
      out.write("   \t   \r\n");
      out.write("   \t    },\r\n");
      out.write("   \t    error:function(result){\r\n");
      out.write("   \t    \t\r\n");
      out.write("   \t    \t//alert(\"삭제실패\");\r\n");
      out.write("   \t    }\r\n");
      out.write("   \t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var path = \"http://192.168.7.252:48080/wheremasil/uploads/images/posting_img/\";\r\n");
      out.write("var cnt=2;\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\t\r\n");
      out.write("deletePost(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.board.posting_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\");\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tvar temp=1;\r\n");
      out.write("\tvar imgpath=\"default\";\r\n");
      out.write("\r\n");
      out.write("\t$(\"#addFile\").on(\"click\",function(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#fileSection\").append(\"<tr><td height='30' bgcolor='#f7f7f7'><div align='right'><strong> 파일 \"+ cnt++ +\"</strong>&nbsp;&nbsp;</div></td><td height='30' bgcolor='#ffffff'> &nbsp;&nbsp; <input name='upfile1' id='upfile1' type='file'> </td></tr>\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#fileSection\").on(\"change\",\"input[type='file']\",function(){\r\n");
      out.write("\t\t var data =new FormData();\r\n");
      out.write("\t\t data.append(\"file\",jQuery(this).get(0).files[0]);\r\n");
      out.write("\t\t //alert(data);\r\n");
      out.write("\t   \t $.ajax({\r\n");
      out.write("\t       \t    url: '/wheremasil/board/check.do',\r\n");
      out.write("\t       \t  type: \"post\",\r\n");
      out.write("              dataType: \"text\",\r\n");
      out.write("              data: data,\r\n");
      out.write("              // cache: false,\r\n");
      out.write("              processData: false,\r\n");
      out.write("              contentType: false,\r\n");
      out.write("\t       \t    success: function(result){\r\n");
      out.write("\t       \t    \t//alert(path+result);\r\n");
      out.write("\t       \t    \t\r\n");
      out.write("\t       \t    \talert(\"업로드 성공!!\");\r\n");
      out.write("\t       \t    \t\r\n");
      out.write("\t       \t    \t\r\n");
      out.write("\t       \t     var data = CKEDITOR.instances.editor1.getData();\r\n");
      out.write("\t       \t     //var data = \"<![CDATA[\"+data1+\"]]>\";\r\n");
      out.write("\r\n");
      out.write("delay(4000);\r\n");
      out.write("\t       \t    \t\r\n");
      out.write("\t       \t    \t\r\n");
      out.write("\t       \t    //\talert(data+\"<img src='\"+path+result+\"'/>\");\r\n");
      out.write("\t       \t    \t$(\"#sumname\").attr('value',path+result); \r\n");
      out.write("\t       \t    \tif(($('input[name=\"upfile1_pos\"]:checked').val())==0){\r\n");
      out.write("\t       \t    \tCKEDITOR.instances.editor1.setData(data+\"<img src='\"+path+result+\"'/>\");\r\n");
      out.write("\t       \t    \t}else{\r\n");
      out.write("\t       \t    \tCKEDITOR.instances.editor1.setData(\"<img src='\"+path+result+\"'/>\"+data);\r\n");
      out.write("\t       \t    \t}\r\n");
      out.write("\t       \t    \t\r\n");
      out.write("\t       \t    \t\r\n");
      out.write("\t       \t    },\r\n");
      out.write("\t       \t    error:function(result){\r\n");
      out.write("\t       \t    \t//alert(result);\r\n");
      out.write("\t       \t    \talert(\"실패\");\r\n");
      out.write("\t       \t    }\r\n");
      out.write("\t       \t});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("       \r\n");
      out.write("       \r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#titleimg\").on(\"change\",function(){\r\n");
      out.write("\t\t//alert(\"대표이미지 삽입이벤트\");\r\n");
      out.write("\t\tvar data =new FormData();\r\n");
      out.write("\t\t data.append(\"file\",jQuery(this).get(0).files[0]);\r\n");
      out.write("\t\t alert(data);\r\n");
      out.write("\t   \t $.ajax({\r\n");
      out.write("\t       \t    url: '/wheremasil/board/check.do',\r\n");
      out.write("\t       \t  type: \"post\",\r\n");
      out.write("             dataType: \"text\",\r\n");
      out.write("             data: data,\r\n");
      out.write("             // cache: false,\r\n");
      out.write("             processData: false,\r\n");
      out.write("             contentType: false,\r\n");
      out.write("\t       \t    success: function(result){\r\n");
      out.write("\t       \t    \t//alert(path+result);\r\n");
      out.write("\t       \t    \t\r\n");
      out.write("\t       \t    \talert(\"업로드 성공!!\");\r\n");
      out.write("\t       \t    \t\r\n");
      out.write("\t       \t    \t\r\n");
      out.write("\t       \t     var data = CKEDITOR.instances.editor1.getData();\r\n");
      out.write("\t       \t     //var data = \"<![CDATA[\"+data1+\"]]>\";\r\n");
      out.write("\r\n");
      out.write("$(\"#sumname\").attr('value',path+result); \r\n");
      out.write("\t       \t    \t\r\n");
      out.write("\t       \t    \t\r\n");
      out.write("\t       \t    //\talert(data+\"<img src='\"+path+result+\"'/>\");\r\n");
      out.write("\t       \t    \t\r\n");
      out.write("\t       \t    \t\r\n");
      out.write("\t       \t    \t\r\n");
      out.write("\t       \t    },\r\n");
      out.write("\t       \t    error:function(result){\r\n");
      out.write("\t       \t    \talert(result);\r\n");
      out.write("\t       \t    \talert(\"실패\");\r\n");
      out.write("\t       \t    }\r\n");
      out.write("\t       \t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#main\").submit(function(event){\r\n");
      out.write("\t\t//alert(\"섭밋전 이벤트호출\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif($(\"#sumname\").val()==\"2\"){\r\n");
      out.write("\t\t\tif(imgpath==\"default\"){\r\n");
      out.write("\t\t\t//alert(\"이미지, 초기이미지 아무것도안넘\");\r\n");
      out.write("\t\t\t$(\"#sumname\").attr('value',imgpath); \r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t//alert(\"2라면\");\r\n");
      out.write("\t\t\t$(\"#sumname\").attr('value',imgpath); \r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t//alert(\"아니라면\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\treturn true;\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#cancle_btn\").on(\"click\",function(){\r\n");
      out.write("\t\t//alert(\"켄슬이벤트\");\r\n");
      out.write("\t\tvar result = confirm('Are you sure you want to do this?');\r\n");
      out.write("\r\n");
      out.write("\t    if(result) {\r\n");
      out.write("\t       //yes\r\n");
      out.write("\t        location.replace('/wheremasil/board/review.do');\r\n");
      out.write("\t    } else {\r\n");
      out.write("\t        //no\r\n");
      out.write("\t    }\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t//alert(\"re\");\r\n");
      out.write("\t\r\n");
      out.write("\t//alert( $(\"#con\").val());\r\n");
      out.write("\tCKEDITOR.instances.editor1.setData( $(\"#con\").val());\r\n");
      out.write("\t$(\"#sumname\").attr('value',$(\"#con2\").val()); \r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=EUC-KR\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body text=\"#000000\" topmargin=\"0\" leftmargin=\"0\" bgcolor=\"#ffffff\" marginheight=\"0\" marginwidth=\"0\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("글쓰기폼\r\n");
      out.write("<form action=\"/wheremasil/board/insertBoardDAO.do\" enctype=\"multipart/form-data\" method=\"post\" name=\"main\" id=\"main\">\r\n");
      out.write("<table width=\"950\" border=\"1\" cellspacing=\"1\" cellpadding=\"0\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                      <tbody><tr>\r\n");
      out.write("                      <input type=\"hidden\" id=\"con2\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.board.p_img_path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"/>\r\n");
      out.write("                      <input type=\"hidden\" name=\"dateTime\" value=\"1\" />\r\n");
      out.write("                      <input type=\"hidden\" name=\"sumname\" id=\"sumname\" value =\"2\" />\r\n");
      out.write("                      <input type=\"hidden\" name=\"con\" id=\"con\" value='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.board.p_content}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("'/>\r\n");
      out.write("                        <td width=\"100\" height=\"35\" bgcolor=\"#f7f7f7\"><div align=\"right\"><font color=\"#ff0000\"></font><strong>닉네임\r\n");
      out.write("                            &nbsp;</strong> </div></td>\r\n");
      out.write("                        <td height=\"35\" bgcolor=\"#ffffff\">\r\n");
      out.write("\t\t\t\t\t\t&nbsp; <input name=\"name\" type=\"text\" size=\"14\" maxlength=\"10\" readonly=\"\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.login_info.member_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("                      </tr>\r\n");
      out.write("                      <tr>\r\n");
      out.write("                        <td width=\"80\" height=\"35\" bgcolor=\"#f7f7f7\"><div align=\"right\"><font color=\"#ff0000\"></font><strong>테마&nbsp;</strong> </div></td>\r\n");
      out.write("                        <td height=\"35\" style=\"padding: 0px 4px;\" bgcolor=\"#ffffff\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<select name=\"theme\" id=\"theme\"  style=\"width: 138px;\" >\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"1\">가족여행</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"2\">연인여행</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"3\">혼자여행</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"4\">우정여행</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"4\">기타</option>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("                      </td>\r\n");
      out.write("                      </tr>\r\n");
      out.write("                      \r\n");
      out.write("                      <tr>\r\n");
      out.write("                      <td height=\"30\" width=\"30\"bgcolor=\"#f7f7f7\"><div align=\"right\"><font size='2'><strong>대표이미지설정 </strong></font>&nbsp;&nbsp;</div></td>\r\n");
      out.write("                      <td height=\"30\" bgcolor=\"#ffffff\"> &nbsp;&nbsp; <input name=\"titleimg\" id=\"titleimg\" type=\"file\">\r\n");
      out.write("\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t \r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("                      \t  <tr>\r\n");
      out.write("                        <td height=\"35\" bgcolor=\"#f7f7f7\"><div align=\"right\"><strong>제목 &nbsp;</strong></div></td>\r\n");
      out.write("                        <td height=\"35\" bgcolor=\"#ffffff\"> &nbsp;   <input name=\"subject\" id=\"subject\" type=\"text\" size=\"80\" maxlength=\"40\" required value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.board.p_title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("                          &nbsp;</td>\r\n");
      out.write("                      </tr>\r\n");
      out.write("                      \r\n");
      out.write("                      \r\n");
      out.write("                                        \r\n");
      out.write("                      \r\n");
      out.write("                      \r\n");
      out.write("                      \r\n");
      out.write("                      \r\n");
      out.write("                      \r\n");
      out.write("                      \r\n");
      out.write("                      <tr>\r\n");
      out.write("                      \r\n");
      out.write("                       <td width=\"80\" height=\"35\" bgcolor=\"#f7f7f7\"><div align=\"right\"><font color=\"#ff0000\"></font><strong>내용&nbsp;</strong> </div></td>\r\n");
      out.write("                        <td height=\"35\" style=\"padding: 0px 4px;\" bgcolor=\"#ffffff\">\r\n");
      out.write("                        \r\n");
      out.write("                         <textarea name=\"editor1\" id=\"editor1\" rows=\"10\" cols=\"100\" class=\"editor1\" >\r\n");
      out.write("                \r\n");
      out.write("            </textarea>\r\n");
      out.write("            <script>\r\n");
      out.write("                // Replace the <textarea id=\"editor1\"> with a CKEditor\r\n");
      out.write("                // instance, using default configuration.\r\n");
      out.write("                CKEDITOR.replace( 'editor1' );\r\n");
      out.write("            </script>\r\n");
      out.write("                        </td>\r\n");
      out.write("                       \r\n");
      out.write("                      </tr>\r\n");
      out.write("  \r\n");
      out.write("<tr>\r\n");
      out.write("                        <td height=\"40\" align=\"center\" bgcolor=\"#f7f7f7\" colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t<font color=\"red\">\r\n");
      out.write("\t\t\t\t\t\t아래 그림파일은 1MB(메가바이트)이하의 그림파일만 올릴 수 있습니다.(JPG,PNG,BMP) <br>\r\n");
      out.write("\t\t\t\t\t\t서버 부하 때문에 GIF파일은 200KB까지만 가능합니다.\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</font>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("                      </tr>             \r\n");
      out.write("                      \r\n");
      out.write("                      \r\n");
      out.write("                      <table width=\"950\" border=\"1\" cellspacing=\"1\" cellpadding=\"0\" id=\"fileSection\">\r\n");
      out.write("                      <tr>\r\n");
      out.write("                      <td height=\"30\" bgcolor=\"#f7f7f7\"><div align=\"right\"><strong>파일1 </strong>&nbsp;&nbsp;</div></td>\r\n");
      out.write("                      <td height=\"30\" bgcolor=\"#ffffff\"> &nbsp;&nbsp; <input name=\"upfile1\" id=\"upfile1\" type=\"file\">\r\n");
      out.write("\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\t<input name=\"upfile1_pos\" type=\"radio\" value=\"1\">맨위 <input name=\"upfile1_pos\" type=\"radio\" checked=\"\" value=\"0\">맨아래\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" value=\"파일추가\" id=\"addFile\" >\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t \r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("<table width=\"950\" border=\"1\" cellspacing=\"1\" cellpadding=\"0\" >\r\n");
      out.write("                    <tr>\r\n");
      out.write("                      <td height=\"50\" style=\"text-align: center;\" bgcolor=\"#f7f7f7\" colspan=\"2\">\r\n");
      out.write("                        \t                        \t<div style=\"margin: 4px 0px;\">\r\n");
      out.write("                        \t                        \t\r\n");
      out.write("                            \t<input name=\"confirm_btn\" type=\"submit\" value=\"     확       인     \">\r\n");
      out.write("                            \t<input name=\"cancle_btn\" type=\"button\"  id=\"cancle_btn\" value=\"     취       소     \">\r\n");
      out.write("                            \t\r\n");
      out.write("                            </div>\r\n");
      out.write("                            \r\n");
      out.write("                            \r\n");
      out.write("                            \r\n");
      out.write("                        </td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
