/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.62
 * Generated at: 2015-06-16 04:28:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.body.plan;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class schedule_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"//apis.daum.net/maps/maps3.js?apikey=8090c845eb21bcc92becc6f8f3bf61fa&libraries=services\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\r\n");
      out.write("\t\tvar jsonData = $.parseJSON('{\"planDetailList\":");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.planDetailList}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("}');\r\n");
      out.write("\t\tvar data = jsonData.planDetailList;\r\n");
      out.write("\t\tvar content;\r\n");
      out.write("\t\tvar totalCost = 0;\r\n");
      out.write("\t\tvar writeFlg = false;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar total_food = 0;\r\n");
      out.write("\t\tvar total_vehicle = 0;\r\n");
      out.write("\t\tvar total_stay = 0;\r\n");
      out.write("\t\tvar total_etc = 0;\r\n");
      out.write("\t\tvar total_cost = 0;\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// map\r\n");
      out.write("\t    var mapContainer = document.getElementById('scheduleMap'), // 지도를 표시할 div \r\n");
      out.write("\t    mapOption = { \r\n");
      out.write("\t        center: new daum.maps.LatLng(data[0].aLatitude, data[0].aLongitude), // 지도의 중심좌표\r\n");
      out.write("\t        level: 3 // 지도의 확대 레벨\r\n");
      out.write("\t    };\r\n");
      out.write("\t\t// 지도를 표시할 div와  지도 옵션으로  지도를 생성\r\n");
      out.write("\t\tvar map = new daum.maps.Map(mapContainer, mapOption);\r\n");
      out.write("\t\tmap.addOverlayMapTypeId(daum.maps.MapTypeId.TERRAIN);\r\n");
      out.write("\t\tvar bounds = map.getBounds();\r\n");
      out.write("\t\tvar schedulePath = [];\r\n");
      out.write("\t\tvar polyline = new daum.maps.Polyline();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#tile_left_nav\").css(\"visibility\", \"hidden\");\r\n");
      out.write("\t\t$(\"#tile_right_nav\").css(\"visibility\", \"hidden\");\r\n");
      out.write("\t\t$(\".left_nav\").css(\"width\", \"0px\");\r\n");
      out.write("\t\t$(\".right_nav\").css(\"width\", \"0px\");\r\n");
      out.write("\t\t$(\"#schedule_startDate\").text(data[0].startDate);\r\n");
      out.write("\t\t$(\"#schedule_endDate\").text(data[data.length - 1].endDate);\r\n");
      out.write("\r\n");
      out.write("\t\t$.each(data, function(idx) {\r\n");
      out.write("\t\t\tif (data[idx].seq == \"1\") {\r\n");
      out.write("\t\t\t\tif (writeFlg) {\r\n");
      out.write("\t\t\t\t\twriteFlg = !writeFlg;\r\n");
      out.write("\t\t\t\t\tcontent += '<div style=\"clear:both;\"><p>' + data[idx].memo + '</p></div>' +\r\n");
      out.write("\t\t\t\t\t'<hr style=\"margin:0 auto;padding:0 auto;\"/><p>총 경비 : ' + totalCost + '원</p><hr style=\"margin:0 auto;padding:0 auto;\"/></div>';\r\n");
      out.write("\t\t\t\t\t$(\"#schedule_root\").append(content);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\ttotal_cost += parseInt(totalCost, 10);\r\n");
      out.write("\t\t\t\t\ttotalCost = 0;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\twriteFlg = !writeFlg;\r\n");
      out.write("\t\t\t\tcontent = '<div class=\"schedule_container itembox day\"><div style=\"padding-top:10px;\">' +\r\n");
      out.write("\t\t\t\t\tdata[idx].curDate.substring(5) + '<hr style=\"margin-top:5px;margin-bottom:5px;\"/></div>';\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tcontent += '<div style=\"width:96%;padding:2%;border-bottom: 1px solid #DDD;\"><div class=\"infoview_image_block\"><img src=\"' +\r\n");
      out.write("\t\t\t\tdata[idx].areaImagePath + '\" class=\"infoview_image\"></div><div class=\"infoview_text_block\" style=\"margin-top:20px;\"><p class=\"infoview_text_title\"><b>' +\r\n");
      out.write("\t\t\t\tdata[idx].areaTitle + '</b></p><p class=\"infoview_text_content\">' +\r\n");
      out.write("\t\t\t\tdata[idx].areaAddress + '</p></div>' +\r\n");
      out.write("\t\t\t\t'<div style=\"clear:both;padding-top:10px;\"><p>식비 : ' + data[idx].costFood+ ' , &nbsp;&nbsp;교통 : ' + data[idx].costVehicle+ '</p>' +\r\n");
      out.write("\t\t\t\t'<p>숙박 : ' + data[idx].costStay+ ' , &nbsp;&nbsp;기타 : ' + data[idx].costEtc+ '</p></div>' +\r\n");
      out.write("\t\t\t\t'</div>';\r\n");
      out.write("\t\t\ttotalCost += parseInt(data[idx].costFood, 10) + parseInt(data[idx].costVehicle, 10) + parseInt(data[idx].costStay, 10) + parseInt(data[idx].costEtc, 10);\r\n");
      out.write("\t\t\ttotal_food += parseInt(data[idx].costFood, 10);\r\n");
      out.write("\t\t\ttotal_vehicle += parseInt(data[idx].costVehicle, 10);\r\n");
      out.write("\t\t\ttotal_stay += parseInt(data[idx].costStay, 10);\r\n");
      out.write("\t\t\ttotal_etc += parseInt(data[idx].costEtc, 10);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar latLng = new daum.maps.LatLng(data[idx].aLatitude, data[idx].aLongitude);\r\n");
      out.write("\t\t\tbounds.extend(latLng);\r\n");
      out.write("    \t\tschedulePath.push(latLng);\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\ttotal_cost += parseInt(totalCost, 10);\r\n");
      out.write("\t\tcontent += '<div style=\"clear:both;\">' + data[data.length - 1].memo + '</div>' +\r\n");
      out.write("\t\t'<hr style=\"margin:0 auto;padding:0 auto;\"/><p>총 경비 : ' + totalCost + '원</p><hr style=\"margin:0 auto;padding:0 auto;\"/></div>';\r\n");
      out.write("\t\t$(\"#schedule_root\").append(content);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#total_food\").text(total_food + \"원\");\r\n");
      out.write("\t\t$(\"#total_vehicle\").text(total_vehicle + \"원\");\r\n");
      out.write("\t\t$(\"#total_stay\").text(total_stay + \"원\");\r\n");
      out.write("\t\t$(\"#total_etc\").text(total_etc + \"원\");\r\n");
      out.write("\t\t$(\"#total_cost\").text(total_cost + \"원\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar slide_width = $(\"#schedule_root\").children(\":first\").width();\r\n");
      out.write("\t\tvar slide_left = 120;\r\n");
      out.write("\t\tvar space = 5;\r\n");
      out.write("\t\t\r\n");
      out.write("\t    var slider = $(\"#schedule_root\");\r\n");
      out.write("\t    var slideArray = $(\"#schedule_root\").children();\r\n");
      out.write("\t    var slideMax = slideArray.length - 1;\r\n");
      out.write("\t    var curSlideNo = 0;\r\n");
      out.write("\t    for (i = 0; i <= slideMax; i++) {\r\n");
      out.write("\t        if (i == curSlideNo) {\r\n");
      out.write("\t        \tslideArray[i].style.left = slide_left + \"px\";\r\n");
      out.write("\t        } else {\r\n");
      out.write("\t        \tslideArray[i].style.left = (slide_left + ((slide_width + space) * i)) + \"px\";\r\n");
      out.write("\t        }\r\n");
      out.write("\t    }\r\n");
      out.write("\t    \r\n");
      out.write("\t    var aniStart = false;\r\n");
      out.write("\t    var next = 1;\r\n");
      out.write("\t    function sliding(targetX, endX, literal){\r\n");
      out.write("\t        var newTargetX = targetX + literal;\r\n");
      out.write("\t        \r\n");
      out.write("\t        if (literal < 0 && newTargetX <= endX) {\r\n");
      out.write("\t            curSlideNo++;\r\n");
      out.write("\t        \tfor (i = 0; i <= slideMax; i++) {\r\n");
      out.write("\t    \t        if (i == curSlideNo) {\r\n");
      out.write("\t    \t        \tslideArray[i].style.left = slide_left + \"px\";\r\n");
      out.write("\t    \t        } else if (i < curSlideNo) {\r\n");
      out.write("\t    \t        \tslideArray[i].style.left = (slide_left - ((slide_width + space) * (curSlideNo - i))) + \"px\";\r\n");
      out.write("\t    \t        } else if (i > curSlideNo) {\r\n");
      out.write("\t    \t        \tslideArray[i].style.left = (slide_left + ((slide_width + space) * (i - curSlideNo))) + \"px\";\r\n");
      out.write("\t    \t        }\r\n");
      out.write("\t    \t    }\r\n");
      out.write("\t            aniStart = false;\r\n");
      out.write("\t            return;\r\n");
      out.write("\t        } else if (literal > 0 && newTargetX >= endX) {\r\n");
      out.write("\t            curSlideNo--;\r\n");
      out.write("\t        \tfor (i = 0; i <= slideMax; i++) {\r\n");
      out.write("\t    \t        if (i == curSlideNo) {\r\n");
      out.write("\t    \t        \tslideArray[i].style.left = slide_left + \"px\";\r\n");
      out.write("\t    \t        } else if (i < curSlideNo) {\r\n");
      out.write("\t    \t        \tslideArray[i].style.left = (slide_left - ((slide_width + space) * (curSlideNo - i))) + \"px\";\r\n");
      out.write("\t    \t        } else if (i > curSlideNo) {\r\n");
      out.write("\t    \t        \tslideArray[i].style.left = (slide_left + ((slide_width + space) * (i - curSlideNo))) + \"px\";\r\n");
      out.write("\t    \t        }\r\n");
      out.write("\t    \t    }\r\n");
      out.write("\t            aniStart = false;\r\n");
      out.write("\t            return;\r\n");
      out.write("\t        }\r\n");
      out.write("\t    \tfor (i = 0; i <= slideMax; i++) {\r\n");
      out.write("\t\t        slideArray[i].style.left = (parseInt(slideArray[i].style.left, 10) + literal) + \"px\";\r\n");
      out.write("\t    \t}\r\n");
      out.write("\t        setTimeout(function () {\r\n");
      out.write("\t            sliding(newTargetX, endX, literal);\r\n");
      out.write("\t        }, 10);\r\n");
      out.write("\t    }\r\n");
      out.write("\t    \r\n");
      out.write("\t    $(\".slide_prev\").on(\"click\", function() {\r\n");
      out.write("\t    \tif (aniStart === true) return;\r\n");
      out.write("\t        next = curSlideNo - 1;\r\n");
      out.write("\t        if (next < 0) return;\r\n");
      out.write("\t        aniStart = true;\r\n");
      out.write("\t        var targetX = parseInt(slideArray[next].style.left, 10);\r\n");
      out.write("\t        var endX = parseInt(slideArray[curSlideNo].style.left, 10);\r\n");
      out.write("\t        sliding(targetX, endX, 30);\r\n");
      out.write("\t    });\r\n");
      out.write("\t    $(\".slide_next\").on(\"click\", function() {\r\n");
      out.write("\t    \tif (aniStart === true) return;\r\n");
      out.write("\t        next = curSlideNo + 1;\r\n");
      out.write("\t        if (next > slideMax - 2) return;\r\n");
      out.write("\t        aniStart = true;\r\n");
      out.write("\t        var targetX = parseInt(slideArray[next].style.left, 10);\r\n");
      out.write("\t        var endX = parseInt(slideArray[curSlideNo].style.left, 10);\r\n");
      out.write("\t        sliding(targetX, endX, -30);\r\n");
      out.write("\t    });\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tmap.setBounds(bounds);\r\n");
      out.write("\t\tpolyline = new daum.maps.Polyline({\r\n");
      out.write("\t\t\tmap: map,\r\n");
      out.write("\t\t\tpath: schedulePath,\r\n");
      out.write("\t\t\tstrokeWeight: 2, // 선의 두께\r\n");
      out.write("\t\t\tstrokeColor: '#FF0000', // 선 색\r\n");
      out.write("\t\t\tstrokeOpacity: 0.7, // 선 투명도\r\n");
      out.write("\t\t\tstrokeStyle: 'solid' // 선 스타일\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\tpolyline.setMap(map);\r\n");
      out.write("\r\n");
      out.write("\t});// end of ready\r\n");
      out.write("\t\r\n");
      out.write("\twindow.onkeydown = function() {\r\n");
      out.write("\t\tvar kcode = event.keyCode;\r\n");
      out.write("\t\tif(kcode == 8 || kcode == 116) event.returnValue = false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<div class=\"schedule_container\">\r\n");
      out.write("\t<div id=\"schedule_itembox\" class=\"schedule_container itembox\">\r\n");
      out.write("\t\t<button class=\"slide_prev\"></button>\r\n");
      out.write("\t\t<div><h2><b id=\"schedule_startDate\"></b><b>&nbsp;&nbsp;~&nbsp;&nbsp;</b><b id=\"schedule_endDate\"></b></h2></div>\r\n");
      out.write("\t\t<div id=\"schedule_root\" class=\"schedule_container itembox root\"></div>\r\n");
      out.write("\t\t<button class=\"slide_next\"></button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"schedule_container side\">\r\n");
      out.write("\t\t<div id=\"scheduleMap\" class=\"schedule_container side map\"></div>\r\n");
      out.write("\t\t<div class=\"schedule_container side cost\">\r\n");
      out.write("\t\t<table class=\"type08\" style=\"width:100%;\">\r\n");
      out.write("\t\t    <thead>\r\n");
      out.write("\t\t\t    <tr>\r\n");
      out.write("\t\t\t        <th colspan=\"4\"><img src =\"/wheremasil/uploads/images/icon/Check_box_32.png\">여행경비정리</th>\r\n");
      out.write("\t\t\t    </tr>\r\n");
      out.write("\t\t    </thead>\r\n");
      out.write("\t\t    <tbody>\r\n");
      out.write("\t\t\t    <tr>\r\n");
      out.write("\t\t\t        <th scope=\"row\">식비</th>\r\n");
      out.write("\t\t\t        <td><span id=\"total_food\"></span></td>\r\n");
      out.write("\t\t\t        <th scope=\"row\">교통비</th>\r\n");
      out.write("\t\t\t        <td><span id=\"total_vehicle\"></span></td>\r\n");
      out.write("\t\t\t    </tr>\r\n");
      out.write("\t\t\t    <tr>\r\n");
      out.write("\t\t\t        <th scope=\"row\">숙박비</th>\r\n");
      out.write("\t\t\t        <td><span id=\"total_stay\"></span></td>\r\n");
      out.write("\t\t\t        <th scope=\"row\">기타</th>\r\n");
      out.write("\t\t\t        <td><span id=\"total_etc\"></span></td>\r\n");
      out.write("\t\t\t    </tr>\r\n");
      out.write("\t\t\t    <tr>\r\n");
      out.write("\t\t\t        <th scope=\"row\">총 금액</th>\r\n");
      out.write("\t\t\t        <td colspan=\"3\"><span id=\"total_cost\"></span></td>\r\n");
      out.write("\t\t\t    </tr>\r\n");
      out.write("\t\t    </tbody>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t\t<input type=\"button\" class=\"submit_plan\" value=\"완료\" onClick=\"location.href='/wheremasil/index.do';\" style=\"margin-top:10px;\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
